extern const GeoLayout normalcap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout normalcap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout normalcap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout normalcap_geo[];
extern Lights1 normalcap_Eye_Ball__CAP__001_lights;
extern Lights1 normalcap_MetalSugar_001_lights;
extern u8 normalcap_Eye_ci4[];
extern u8 normalcap_Eye_pal_rgba16[];
extern u8 normalcap_Metal_Shade_rgba16_rgba16[];
extern u8 normalcap_Metal_Light_rgba16_rgba16[];
extern Vtx normalcap_Normal_Cap_DL_mesh_layer_4_vtx_0[94];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_normalcap_Eye_Ball__CAP__001[];
extern Gfx mat_revert_normalcap_Eye_Ball__CAP__001[];
extern Gfx mat_normalcap_MetalSugar_001[];
extern Gfx mat_revert_normalcap_MetalSugar_001[];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_4[];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_4_mat_override_MetalSugar_001_0[];
extern Gfx normalcap_material_revert_render_settings[];
