extern const GeoLayout normalcap_Normal_Cap_State_Switch_opt1[];
extern const GeoLayout normalcap_Normal_Cap_State_Switch_opt2[];
extern const GeoLayout normalcap_Normal_Cap_State_Switch_opt3[];
extern const GeoLayout normalcap_geo[];
extern Lights1 normalcap_HeadEyeSclera_lights;
extern Lights1 normalcap_HeadEyePupil_lights;
extern Lights1 normalcap_Metal__METAL__lights;
extern u8 normalcap_Eyes_ia8[];
extern u8 normalcap_Metal_Shade_rgba16_rgba16[];
extern u8 normalcap_Metal_Light_rgba16_rgba16[];
extern Vtx normalcap_Normal_Cap_DL_mesh_layer_1_vtx_0[81];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_1_tri_0[];
extern Vtx normalcap_Normal_Cap_DL_mesh_layer_4_vtx_0[12];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_4_tri_0[];
extern Gfx mat_normalcap_HeadEyeSclera[];
extern Gfx mat_revert_normalcap_HeadEyeSclera[];
extern Gfx mat_normalcap_HeadEyePupil[];
extern Gfx mat_revert_normalcap_HeadEyePupil[];
extern Gfx mat_normalcap_Metal__METAL_[];
extern Gfx mat_revert_normalcap_Metal__METAL_[];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_1[];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_4[];
extern Gfx normalcap_Normal_Cap_DL_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx normalcap_material_revert_render_settings[];
