extern const GeoLayout metalcap_Metal_Cap_State_Switch_opt1[];
extern const GeoLayout metalcap_Metal_Cap_State_Switch_opt2[];
extern const GeoLayout metalcap_Metal_Cap_State_Switch_opt3[];
extern const GeoLayout metalcap_geo[];
extern Lights1 metalcap_MetalSugar_lights;
extern Lights1 metalcap_Metal__METAL__lights;
extern u8 metalcap_Metal_Shade_rgba16_rgba16[];
extern u8 metalcap_Metal_Light_rgba16_rgba16[];
extern u8 metalcap_Metal_Shade_rgba16_rgba16_copy[];
extern u8 metalcap_Metal_Light_rgba16_rgba16_copy[];
extern Vtx metalcap_Metal_Cap_DL_mesh_layer_1_vtx_0[94];
extern Gfx metalcap_Metal_Cap_DL_mesh_layer_1_tri_0[];
extern Gfx mat_metalcap_MetalSugar[];
extern Gfx mat_revert_metalcap_MetalSugar[];
extern Gfx mat_metalcap_Metal__METAL_[];
extern Gfx mat_revert_metalcap_Metal__METAL_[];
extern Gfx metalcap_Metal_Cap_DL_mesh_layer_1[];
extern Gfx metalcap_Metal_Cap_DL_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx metalcap_material_revert_render_settings[];
