extern const GeoLayout wingcap_Wing_Cap_Switch_opt1[];
extern const GeoLayout wingcap_Wing_Cap_Switch_opt2[];
extern const GeoLayout wingcap_Wing_Cap_Switch_opt3[];
extern const GeoLayout wingcap_geo[];
extern Lights1 wingcap_Eye_Ball__CAP__001_lights;
extern Lights1 wingcap_Metal__METAL__001_lights;
extern u8 wingcap_wing_2_ia8[];
extern u8 wingcap_wing1_ia8[];
extern u8 wingcap_Eye_ci4[];
extern u8 wingcap_Eye_pal_rgba16[];
extern u8 wingcap_Metal_Shade_rgba16_rgba16[];
extern u8 wingcap_Metal_Light_rgba16_rgba16[];
extern Vtx wingcap_Wing_Cap_mesh_layer_4_vtx_0[8];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_tri_0[];
extern Vtx wingcap_Wing_Cap_mesh_layer_4_vtx_1[8];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_tri_1[];
extern Vtx wingcap_Wing_Cap_mesh_layer_4_vtx_2[94];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_tri_2[];
extern Gfx mat_wingcap_Wing_Tip_005[];
extern Gfx mat_revert_wingcap_Wing_Tip_005[];
extern Gfx mat_wingcap_Wing_Base_005[];
extern Gfx mat_revert_wingcap_Wing_Base_005[];
extern Gfx mat_wingcap_Eye_Ball__CAP__001[];
extern Gfx mat_revert_wingcap_Eye_Ball__CAP__001[];
extern Gfx mat_wingcap_Metal__METAL__001[];
extern Gfx mat_revert_wingcap_Metal__METAL__001[];
extern Gfx wingcap_Wing_Cap_mesh_layer_4[];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_mat_override_Metal__METAL__001_0[];
extern Gfx wingcap_material_revert_render_settings[];
