extern const GeoLayout wingcap_Wing_Cap_Switch_opt1[];
extern const GeoLayout wingcap_Wing_Cap_Switch_opt2[];
extern const GeoLayout wingcap_Wing_Cap_Switch_opt3[];
extern const GeoLayout wingcap_geo[];
extern Lights1 wingcap_HeadEyeSclera_lights;
extern Lights1 wingcap_HeadEyePupil_lights;
extern Lights1 wingcap_Wing_Tip_lights;
extern Lights1 wingcap_Wing_Base_lights;
extern Lights1 wingcap_Metal__METAL__lights;
extern u8 wingcap_Eyes_ia8[];
extern u8 wingcap_wing_2_ia8[];
extern u8 wingcap_wing1_ia8[];
extern u8 wingcap_Metal_Shade_rgba16_rgba16[];
extern u8 wingcap_Metal_Light_rgba16_rgba16[];
extern Vtx wingcap_Wing_Cap_mesh_layer_1_vtx_0[81];
extern Gfx wingcap_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx wingcap_Wing_Cap_mesh_layer_4_vtx_0[12];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_tri_0[];
extern Vtx wingcap_Wing_Cap_mesh_layer_4_vtx_1[8];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_tri_1[];
extern Vtx wingcap_Wing_Cap_mesh_layer_4_vtx_2[8];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_tri_2[];
extern Gfx mat_wingcap_HeadEyeSclera[];
extern Gfx mat_revert_wingcap_HeadEyeSclera[];
extern Gfx mat_wingcap_HeadEyePupil[];
extern Gfx mat_revert_wingcap_HeadEyePupil[];
extern Gfx mat_wingcap_Wing_Tip[];
extern Gfx mat_revert_wingcap_Wing_Tip[];
extern Gfx mat_wingcap_Wing_Base[];
extern Gfx mat_revert_wingcap_Wing_Base[];
extern Gfx mat_wingcap_Metal__METAL_[];
extern Gfx mat_revert_wingcap_Metal__METAL_[];
extern Gfx wingcap_Wing_Cap_mesh_layer_1[];
extern Gfx wingcap_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0[];
extern Gfx wingcap_Wing_Cap_mesh_layer_4[];
extern Gfx wingcap_Wing_Cap_mesh_layer_4_mat_override_Metal__METAL__0[];
extern Gfx wingcap_material_revert_render_settings[];
